global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway-service:8000"]

  - job_name: "auth"
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "project"
    static_configs:
      - targets: ["project-service:8000"]

  - job_name: "billing"
    static_configs:
      - targets: ["billing-service:8000"]

  - job_name: "notification"
    static_configs:
      - targets: ["notification-service:8000"]

  - job_name: "analytics"
    static_configs:
      - targets: ["analytics-service:8000"]
